baseURL = "https://lamaaustin.com"
languageCode = "en-us"
title = "LAMA Austin"

[params]
  description = "Latin American Motorcyclists Association – Austin, Texas Chapter"
  facebook = "https://facebook.com/lamaaustin"
  instagram = "https://instagram.com/lamaaustin"

[markup.goldmark.renderer]
  unsafe = true
